### ISSUE TITLE
[iOS]Navigation Bar rendering in wrong height on launch on notched devices

### ISSUE THREAD

**Issue by kazedayo** [RiceCakess/Holodex#104]
on iOS platform, the navigation bar renders in wrong height only on first launch on all notched devices
After performing a pull-to-refresh, the navigation bar renders in the correct height
The same bug also happens in the navigation drawer
Here is a short clip to better illustrate the bug:
![](https://i.ibb.co/tMW5RGH/Clean-Shot-2021-03-29-at-17-54-36.gif)

I think it has something to do with the getHeight() function in MainNav.vue and safeHeight() function in NavDrawer.vue

**Comment by sphinxrave** [comment]
Finally fixed #117
