### ISSUE TITLE
Youtube video quality button in music feature

### ISSUE THREAD

**Issue by pitekiren** [RiceCakess/Holodex#105]
Please add video quality control button, I often play a karaoke video at 144p.

**Comment by RiceCakess** [comment]
The quality button is hidden for video sizes under 405px. 

Current work around: full screen the video, set the desired quality, unfullscreen.

Maybe a button to expand the window/player temporarily, or a quality selector?

**Comment by sphinxrave** [comment]
> The documentation has been updated to reflect the fact that the API no longer supports functions for setting or retrieving playback quality. As explained in this YouTube Help Center article, to give you the best viewing experience, YouTube adjusts the quality of your video stream based on your viewing conditions.
> 
> The changes explained below have been in effect for more than one year. This update merely aligns the documentation with current functionality:
> 
>     The getPlaybackQuality, setPlaybackQuality, and getAvailableQualityLevels functions are no longer supported. In particular, calls to setPlaybackQuality will be no-op functions, meaning they will not actually have any impact on the viewer's playback experience.
>     The queueing functions for videos and playlists -- cueVideoById, loadVideoById, etc. -- no longer support the suggestedQuality argument. Similarly, if you call those functions using object syntax, the suggestedQuality field is no longer supported. If suggestedQuality is specified, it will be ignored when the request is handled. It will not generate any warnings or errors.
>     The onPlaybackQualityChange event is still supported and might signal a change in the viewer's playback environment. See the Help Center article referenced above for more information about factors that affect playback conditions or that might cause the event to fire.
>

Youtube disabled their media quality controls from outside 👎 so no quality selector. We have to like... idk, rescale this player?
