### ISSUE TITLE
'Favorites' tab shows significantly lower viewer numbers than is correct

### ISSUE THREAD

**Issue by Pieplayerian** [RiceCakess/Holodex#136]
The top image is a screenshot from the 'Home' tab, and the stream numbers are verified to be correct after comparing with both Holodex stream page, as well as the source YouTube stream page.
The bottom image is a screenshot from the 'Favorites' tab, taken less than 30 seconds after the above image was taken.

Home:
![exWatchingHome](https://user-images.githubusercontent.com/43185901/113449002-e899c300-93ca-11eb-92bd-a43e752bcd6b.jpg)
Favorites:
![exWatchingFavorites](https://user-images.githubusercontent.com/43185901/113449116-239bf680-93cb-11eb-8b0b-82d8ce29da00.jpg)

(I'm going to guess that the numbers seen on the 'Favorites' page were only updated when the stream first appeared on the Holodex site. I would verify this before submitting, but the closest stream is 2 hours away.)

**Comment by RiceCakess** [comment]
Fixed, counts should be similar now.
