### ISSUE TITLE
Favorites channels' streams not showing up in favorites tab

### ISSUE THREAD

**Issue by Daegnor** [RiceCakess/Holodex#141]
There are several channels I added to my favorites whose current stream are not showing up in my Favorites tab (their older videos/streams are showing up though). Unfavoriting and favoriting them didn't fix it, neither did reconnecting.

**Comment by sphinxrave** [comment]
seems the favorite system needs a slight rewrite / recheck why these kind of bugs show up.

**Comment by RiceCakess** [comment]
Fixed handling case of deleted channel, and exception handling per key to prevent the cache from failing due to one bad entry
