### ISSUE TITLE
Browsing recent clips listing in paginated mode often jumps to page 1

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#152]
Since around Mar 30th, while browsing the Recent Clips listing in paginated mode, pressing Newer or Older frequently causes the browser to jump to page=1. I see the url bar briefly show the correct page number before it changes. In the network log, I see the client ask for offset=NNN, immediately followed by two requests for offset=0, all caused by a single mouse click.

I have read issue #114 and I suspect that 'fixing' it introduced this issue, since the dates seem to match. The repro instructions there also seem relevant. I believe I can reproduce my bug by opening a second tab, and seeking into the recent clips listing a few times in that tab, before returning to the first tab and trying to seek there.

EDIT: Note that the issue is not limited to just the above reproduction scenario. I also frequently get it while just going through recent clips and opening them on youtube by middle-clicking on the thumbnail portion. Once I'm done with the current page and want to move on to the previous one, I press Newer and get page 1, maybe 50% of the time.

**Comment by sphinxrave** [comment]
This should be harder to hit on recent versions

**Comment by theultramage** [comment]
I can still reproduce it on-demand first try using the steps I provided in the original post.
