### ISSUE TITLE
Unchecked asynchronous data loading while switching pages

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#153]
If I switch pages while a video list in the process of being loaded, the previous asynchronous request still completes and is accepted together with the current one, resulting in a video listing that's twice as long as the intended size, containing items from both requests.

One way to reproduce this is to browse into a video listing, then hit the browser's Back button right after requesting a data load. Another is to open a channel page, switch the view to Clips, then quickly switch it to Videos again.

**Comment by sphinxrave** [comment]
fixed.
