### ISSUE TITLE
Sorting channel name search suggestions based on relevance

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#154]
When I'm looking up a channel by name, and type in a few letters, the suggestions that pop up don't seem to have any particular system or order to them. For channels with overlapping names, sometimes this makes the unwanted results show up first. It is most obvious when searching for 'korone' or 'gura'.

I suggest, if possible, reordering the results in the 'channel' category:

 * Channels from the currently selected organization should appear before all other channels (Inugami Korone vs Korone Pochi)
 * Talent channels should maybe appear before clipper channels ('Coco' ch. vs Felix172 ['Coco' clips only])
 * Full word match should maybe go before partial word match ('Mori' Calliope vs Hime'mori' Luna)

**Comment by RiceCakess** [comment]
Fixed in #182
