### ISSUE TITLE
A way to automatically disable translations.

### ISSUE THREAD

**Issue by JusTaFictioN** [RiceCakess/Holodex#155]
I use LiveTL and having to disable translations every time I enter a stream get very annoying very quickly (not to mention that i can't disable them until some 5 minutes into a stream so if i'm early i can't use LiveTL or the chat would only have space for about 3 messages at a time.

**Comment by sphinxrave** [comment]
This shouldn’t be an issue after the latest release (couple hours ago). Let us know.
