### ISSUE TITLE
Favorites tab shows unfavorited channels in MultiView

### ISSUE THREAD

**Issue by FlyntCola** [RiceCakess/Holodex#162]
After setting several favorites from different groups, I have noticed that some channels I have not set as favorite are still showing up in the Favorites section of the MultiView page. I have specifically noticed this with two channels, Nijisanji JP's Asahina Akane and Nijisanji KR's Bora Nun. I wonder if the favorites selection page might be mixing some IDs up, but have not been using the site long enough to notice any channels that I have set to favorite missing yet. This only seems to affect the MultiView page at the moment, as those channels do not show up in the Favorites listing on my sidebar or as selected when I return to the favorites selection page.

**Comment by sphinxrave** [comment]
![image](https://user-images.githubusercontent.com/62570796/114706820-58b71b80-9cde-11eb-8515-b52d94ed85b5.png)

Asahina Akane is constantly thought of as being in a collab stream with Hisui, as she mentions her channel in every single video. My best guess is just blocking her channel if you don't want her videos showing up.
![image](https://user-images.githubusercontent.com/62570796/114706962-83a16f80-9cde-11eb-865f-fc46dd19fa01.png)

We can definitely optimize this algorithm to remove 100% mentions, so if anyone is interested in working on that kind of algorithm please hit us up.

**Comment by FlyntCola** [comment]
Does the Favorites section of MultiView include collabs as well? If so, that would definitely explain it, and I wouldn't have any problem with that functionality. Just wanted to make sure it wasn't an error.

**Comment by sphinxrave** [comment]
It does indeed. In case your oshi appears on a different channel.
