### ISSUE TITLE
Video and video progress refreshes when window size is changed

### ISSUE THREAD

**Issue by Madekuji** [RiceCakess/Holodex#167]
While watching a video on Holodex, a user may try to change the window size of the browser either by adjusting it or moving the browser tab to a browser window with a larger viewport, resulting in the entire page and the video refreshing, losing the progress on a video. Attached is a use-case where this issue applies:

https://user-images.githubusercontent.com/27665110/114683417-98175380-9d42-11eb-8804-d368aa2779af.mp4

**Comment by sphinxrave** [comment]
We'll make a best attempt at fixing it. The view we draw for Mobile Viewport (essentially the website in mobile mode) is very different compared to the desktop display, causing the interruption, it's possible that our fix won't resolve it though...

**Comment by sphinxrave** [comment]
unfortunately this is a wontfix... fixing it causes another problem to show up (can't continuously play with a PIP on MugenClips), and people don't resize their browser tabs that frequently anyways.
