### ISSUE TITLE
Searching for collabs

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#170]
Currently, putting one or more channels into the search box defines the starting dataset, which is then filtered using additional search terms. If there are none, the result is just an union of all the videos, clips and collabs of all those channels individually. (This is, by the way, an expensive query and a possible DoS vector.)

To find collabs between two channels right now, I have to search for "channel A (type=channel) channel B (type=title/desc)". This should return all collabs of A and B on channel A, all collabs of A and B on channel B (as a technicality of how the first part of the query works), and all collabs on third party channels that reference both A and B. Which is exactly what I'm looking for with this type of query. I think this approach will also work when searching for collabs of 3 or more channels.

Now, I wonder if this can be made more user-friendly. Having to copy-paste in the channel id is awkward, sort of like having to mess with the url bar when looking up a specific video id, before video id search type was implemented. Perhaps if an additional search term type was implemented, 'collab'. Or maybe there's a better way.

**Comment by sphinxrave** [comment]
Fixed, but not released yet. Closing.

**Comment by theultramage** [comment]
From what I've been told, this was fixed by changing the multiple channels behavior from union to intersection.
