### ISSUE TITLE
[Quality of Life] Update page should contain real info or link to github commits

### ISSUE THREAD

**Issue by LittleVulpix** [RiceCakess/Holodex#173]
Oftentimes I am prompted to update Holodex, and it also says I should go check changelog when I update - but it hasn't changed for a few weeks now.

I understand a lot of small changes are being made, but it gets a little confusing. "Did anything update? Is the page just bugged?" etc etc.

So I propose that you either link to github commits when you push an update, or that you put the commits output into the changelog on holodex itself (like it is there for V2.1 for example).

Of course none of this is a must, it is just a request from a user :)

And I forgot to say, I wish youtube was half as competent as you when it comes to making UI! Holodex's layout rocks (even in "single stream mode"!)

**Comment by sphinxrave** [comment]
Addressed by PR #179 , requires one more PR to fully incorporate.

**Comment by sphinxrave** [comment]
fully incorporated by #182 closing in advance of release.

**Comment by LittleVulpix** [comment]
Yay! :D Thank you!
