### ISSUE TITLE
v-skeleton-loader flashing animation cpu load

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#198]
Recently the infocard placeholders during loading have been changed into [vue skeleton loader](https://v2.vuetifyjs.com/en/components/skeleton-loaders/) objects. This involves a box with a grey outline of the infobox, with a white flashing effect looping over it. I noticed that it takes longer to load and the page becomes unresponsive, compared to the previous implementation.

I looked at the html/css code and it turns out that this is not a simple animated gif/png file. This explains why my animation blocker extension wasn't working. It's not even an image. Instead, it is a collection of stacked divs with some complex css styling to make the blocks appear fancy and curved like that. The flashing effect was achieved with an infinitely looping animation transform, using a sliding opaque rectangle overlay (`animation: loading 1.5s infinite;` `transform: translateX(-100%);`).

This flashy unoptimized piece of crap is being rendered in software on the cpu. Just their documentation page causes 30% cpu load (Chrome pages are single-threaded). The animation still plays even when scrolled off-screen. When holodex is loading 24 of these, it drives the core to 100% and I assume the animation drops frames to compensate.

If it is not essential to the user experience, I suggest removing the flashing animation. I myself felt like the previous loading placeholders were fine when I was using the site. The queries usually take a second at most to complete, so it's not like I need something to distract me while I'm waiting.

**Comment by RiceCakess** [comment]
Fixed in #199
