### ISSUE TITLE
Option to customize default page beyond just Home vs Favorites

### ISSUE THREAD

**Issue by planetarian** [RiceCakess/Holodex#211]
With HoloTools, I primarily used the Play page, and I used my browser to 'install' the site as an App, which would open directly to the Play page since that's the page I was on when I 'installed' it.

Holodex, however, seems to expose some sort of metadata that lets the browser actually see it as an App, since it shows the "Install Holodex" icon and whatnot. This is at my detriment, however, since it always opens to the Home/Favorites page no matter how I installed it, so I have to click on MultiView every time I open it.

Even if I edit the URL in the shortcut on my PC, it still opens the site directly to the default page. It's a minor annoyance, but ideally I'd like to see a way to either expand the "Default open Favorites" setting to instead be able to configure exactly which page to open by default (beyond just the two existing options of Home vs Favorites), or have it listen to the URL I'm on when I install the app, or the URL in my app shortcut.

**Comment by sphinxrave** [comment]
Closed by 3a0d1d52015c0fae079cf61c089eabd69b744018
