### ISSUE TITLE
About clear button

### ISSUE THREAD

**Issue by SolomonWarlock** [RiceCakess/Holodex#220]
I accidentally clicked on the clear button when I just wanted to add a new panel. Could you play add in a confirmation pop-up when you click on clear, so we can avoid those kinds of accidents? I was using the site as a convenient place to store some of the archives I was planning to watch later, but those are gone now because of this.

**Comment by RiceCakess** [comment]
Yea we can add something like that, but if you are looking to just save videos to watch later I highly suggest using the save to library button for a watch later list. 

![image](https://user-images.githubusercontent.com/3145205/117553976-9ec77c80-b009-11eb-982f-6f7dd102b4e5.png)

**Comment by SolomonWarlock** [comment]
Ooooh, I didn't know that was a thing, thank you very much!

**Comment by SolomonWarlock** [comment]
Ah, I see that button seems to only be there for upcoming streams, I don't see it for streams that already happened, or other videos/streams I've added in manually.

**Comment by SolomonWarlock** [comment]
Ahhhhhh ok then! Hadn't noticed it also showed there. Thank you so much for help!

**Comment by sphinxrave** [comment]
Too lazy to make a confirmation dialog and have our translators I18N it, instead I added a bit more padding to it and hid it away in a dropdown menu to decrease accidentally Clear-ing. Hope it's sufficient. #222 will release.
