### ISSUE TITLE
Google Login Popup not working

### ISSUE THREAD

**Issue by BurntTuna** [RiceCakess/Holodex#232]
Im using chrome browser in incognito mode and when i try to login with Google Login, the pop up did not appear.

I checked the console and saw some error about cookies.
<img width="933" alt="Screenshot 2021-05-11 at 6 31 31 PM" src="https://user-images.githubusercontent.com/84015930/117801688-2c63d000-b287-11eb-8437-0e04f853d2f5.png">

**Comment by RiceCakess** [comment]
Cookies are blocked by default in incognito, go to settings and choose 'Allow all cookies' 

![image](https://user-images.githubusercontent.com/3145205/117802160-fa605880-b209-11eb-9c91-31de4306c6db.png)
