### ISSUE TITLE
Clips do not reload if the screen size is much longer than wide

### ISSUE THREAD

**Issue by EHummerston** [RiceCakess/Holodex#258]
I am on Chrome with a window size of **1718px x 1359px** (half-screen of wide screen monitor), and my thumbnail/grid size is set to **Small**
When navigating to the clips page the initial load is triggered, but after completing the render of new rows, the next page is not triggered. This is despite the bottom of the page still being in view.

I'm a React user not Vue so I apologise if from here on what I suggest is not practical.

Because the [onIntersect (v-intersect)](https://vuetifyjs.com/en/api/v-intersect/) method is only invoked "on DOM mount and when the element is intersected", the [emitEvent](https://github.com/RiceCakess/Holodex/blob/dev/src/components/common/InfiniteLoad.vue#L56) method of InfiniteLoad.vue will not be triggered unless `isIntersecting` becomes `false` and then `true`. In my use case, it remains true and so `onIntersect` is never invoked after the first render.

If instead there was an `isIntersecting` property of `data`, then watching both `isIntersecting` and `status` could respond to both states that facilitate the `emitEvent` method.

```
// src\components\common\InfiniteLoad.vue
    data() {
        return {
            STATUSES: Object.freeze({
                READY: 0,
                LOADING: 1,
                ERROR: 2,
                COMPLETED: 3,
            }),
            status: 0,
            nextPage: 1,
            // new property    
            isIntersecting: false,
        };
    },
    watch: {
        status() {
            if (this.status === this.STATUSES.READY && this.isIntersecting) this.emitEvent();
        },
        isIntersecting() {
            if (this.status === this.STATUSES.READY && this.isIntersecting) this.emitEvent();
        },
    },
    methods: {
        onIntersect(entries, observer, isIntersecting) {
            // record current state of intersection
            this.isIntersecting = isIntersecting;
        },
        ...
    }
```

sorry if this doesn't make sense I literally only know as much about vue as I just googled for this

**Comment by sphinxrave** [comment]
no this is plenty enough, we thought we fixed this though. odd. Will take another look at it!
