### ISSUE TITLE
Defining behavior when navigating to another menu

### ISSUE THREAD

**Issue by sokcuri** [RiceCakess/Holodex#276]
Currently, if you click another menu on the left sidebar, the currently playing video ends. Similarly for multiview, state is not saved.

It would be nice if the video could be played without any problem even if it was displayed for a while with a mini player like YouTube, or if you save the state and go to another menu.

**Comment by sphinxrave** [comment]
Mini player is really hard to implement, given we've attempted it once in the past and it didn't work out, and we haven't learned anything that'll prevent us from just retracing that failure. 

We do support middle mouse clicks / control clicking in most places for opening in new tab if you like to background the current tab and work on other things.

**Comment by sokcuri** [comment]
Thanks for comments!
