### ISSUE TITLE
Where is Kuzuha？

### ISSUE THREAD

**Issue by CrowMaid** [RiceCakess/Holodex#282]
Choose Nijisanji always no Kuzuha Channel

Why?

**Comment by sphinxrave** [comment]
![image](https://user-images.githubusercontent.com/62570796/120886952-4bfbc900-c5a5-11eb-80f2-976a4ee87f1f.png)

Something like this is the cause, but i don't know why either.

**Comment by sphinxrave** [comment]
ah.... it's fixed.

**Comment by sphinxrave** [comment]
did some backend work to get rid of a bug that affects kuzuha-alike streaming habits.
