### ISSUE TITLE
Feature Request: Manually add channels to favourite list

### ISSUE THREAD

**Issue by clancy-chao** [RiceCakess/Holodex#284]
It would be nice if users can manually add channels to their favourite list.
The vtuber channel request form askes for a business contact which I assume is for the staff to fill.

**Comment by RiceCakess** [comment]
Unfortunately, if the channel isn't added to our system, it won't properly find and tag all their videos. 

Feel free to suggest a channel using that form, ignore the wording and put N/A for contact information
