### ISSUE TITLE
Feature Request: Ability to collapse "Clips" and "Refers" collums while watching full archives of streams

### ISSUE THREAD

**Issue by KoriAnime** [RiceCakess/Holodex#287]
While watching full Archives of streams there are two columns named "Clips" and "Refers" on the right side, that show, as one would expect, the clips and refers related to the Stream. This in itself is a really good feature, but I would love to have the ability to collapse those two, mainly because their titles can contain spoilers for what the stream is going to contain.

This isn't exactly a large issue, but a feature, that would maybe make viewing the stream on Holodex itself a little more enjoyable than before!

(Also this is my first time using github so sorry in case I made a mistake here!)

**Comment by sphinxrave** [comment]
so like... a setting option? or just the ability to do so on the fly? we probably want to keep it expanded by default
![](https://media1.tenor.com/images/791161e590353714bd910a256e0ae99f/tenor.gif?itemid=19258539)

**Comment by KoriAnime** [comment]
I definitely don't really mind it being open by default!

What I meant was being able to close it in the same way you would maybe close something like the different organizations on the channels tab.

Somehow the only example I can think of right now is the way that you can do it with discord (screenshot: https://i.imgur.com/CMR2F4A.png)

"Server Stuff" in the screenshot is expanded as usual while "Information" is collapsed and all the channels are hidden. That kind of thing I thought would be helpful for the clips and Refers columns on Holodex as well.

(Sorry for the weird explanation, somehow I can't English right now)
