### ISSUE TITLE
TLDex does not appear to respect block list

### ISSUE THREAD

**Issue by Vesperindustrial** [RiceCakess/Holodex#297]
In the holodex TL chat pane, I have some usernames that are set to be blocked but they still appear in the translation pane because it also picks up verified accounts (that aren't translations either, just chat comments). I don't want to block all of the verified messages obviously, just ones from specific accounts.

**Comment by RiceCakess** [comment]
Seems like loading from history was not filtering blocked accounts, but new messages were always blocked. If you were seeing blocked accounts show up on new messages, then we should re open this issue.

**Comment by Vesperindustrial** [comment]
Yes you're correct then, it was 'loading from history' that wasnt respecting it as far as I can see.
