### ISSUE TITLE
Some live missing in live/upcoming area

### ISSUE THREAD

**Issue by tommy35hk** [RiceCakess/Holodex#32]
Kureiji Ollie Ch. hololive-ID is streaming but not showing in live/upcoming area.

Stream Topic:【PHASMOPHOBIA】 REAL SOLO RUN!!! 【Hololive Indonesia 2nd Gen】
Link: https://youtu.be/Q30RSJdBh3A

**Comment by RiceCakess** [comment]
Hello, that stream has ended, but if you see another stream missing please let me know
