### ISSUE TITLE
A way to view an item's holodex page when using "Open on Youtube" setting

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#34]
At the moment, when "Open on Youtube" setting is enabled, it is impossible to use the UI to view individual items' holodex pages. The entire area of the item acts as a youtube link, except the part that shows the channel name, and the part that shows the number of clips, if any. It is, for example, not possible to search for a clip by title, open its entry to see the parent stream, and then browse to other clips of the same stream.

I suggest making some portion of the item's area still link to its holodex page. Like the video title, for example. Or, maybe make the thumbnail part a youtube link, and the entire bottom half a holodex link.

**Comment by RiceCakess** [comment]
Forgot that I already made this change in an earlier commit. In redirect mode, clicking on the bottom part of the video will take you to the Holodex page, while clicking on the thumbnail will take you to youtube.
