### ISSUE TITLE
Multiple scheduled streams

### ISSUE THREAD

**Issue by diablo050189** [RiceCakess/Holodex#35]
Sorry, not really sure how to title the issue.  I noticed that if a channel has multiple streams scheduled The side bar will only show the time for the latest stream. Even as I type this message, there is a live stream going on but it doesn't show as live on the sidebar, instead it shows 1hr when the next stream starts and another channel has a stream scheduled for an hour, one in about 3hrs, and one in 11 hours but sidebar shows 11hr instead of the stream in 1hr. Also streams will still  say Live in the sidebar after a stream has ended until you click on the channel then it will disappear and the channel will move down to the bottom of the list.

**Comment by sphinxrave** [comment]
Issue pertains to v1 holodex, closing
