### ISSUE TITLE
Chat stopped working

### ISSUE THREAD

**Issue by leonatoieiri** [RiceCakess/Holodex#39]
For some reason the youtube chat is not loading, maybe something changed from youtube's side.

Tried in another browser and got the same error.

![Screenshot_2021-01-27 Holodex](https://user-images.githubusercontent.com/4553965/106042773-41439b80-60bc-11eb-9746-9f5441048b99.jpg)

**Comment by RiceCakess** [comment]
Hello, we've had quite a few users report this issue, and seems to be a Youtube problem (it's happening on multiple sites with live chat embeds). 

Current steps to fix it is to: close all Holodex/Youtube tabs, then clear both Holodex and Youtube cookies

We are looking to see what we can do to fix it, but it's most likely a Youtube problem, as nothing has changed on our end.

**Comment by RiceCakess** [comment]
Fixed by youtube
