### ISSUE TITLE
Urls in search box

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#42]
It would be nice if the search box could at least understand youtube urls. That is, if a youtube url is submitted as the search query, it should somehow bring up the associated holodex entry.

Right now, it only kinda-sorta works to find clips that contain that url in the description. And even then, it gives different results for the full form vs shortened form, since it's just string matching. Searching for just the video id would find both, I guess.

So what I'm suggesting is search support for full and shortened video urls (for youtube, and maybe other sites in the future?), maybe support for searching just the video id itself, and perhaps channel urls as well.

**Comment by RiceCakess** [comment]
Current workaround exists, where a user on youtube or with a youtube link i.e youtube.com/watch?v=123456 could swap it out for 
holodex.net/watch?v=123456 or holodex.net/watch/123456. The same exists for channel ids, which you can look up by name anyways.

**Comment by sphinxrave** [comment]
Seems to be resolved! Thanks Ash & Michael <3
