### ISSUE TITLE
Datetime format adjustment to avoid word wrapping

### ISSUE THREAD

**Issue by theultramage** [RiceCakess/Holodex#43]
Currently the datetime formatting under older video items is pretty lengthy. It uses the full month name, and it uses the 12-hour AM/PM notation. This causes line wrap on most items when using the most compact layout. Adjusting the format to use short month names would save 1-6 characters. Using the 24-hour notation would save 3 characters but would be undesirable in some regions.

Line wrap is further caused by the addition of the "N clips" text. Nothing can be done for the smallest layout. The medium layout might be able to squeeze it onto a single line if both format adjustments are made. The large layout experiences line breaks for the longest month 'September'.

I've seen that various websites, like forums, provide an user interface option for selecting a preferred datetime format.

My additional observation is that the datetime format is not localized based on UI language setting. If such a thing were implemented, it would affect the above considerations. For example, japanese format might be way more compact; or, some languages might not have abbreviated names for months.

**Comment by RiceCakess** [comment]
The current date time format is based on what is provided by our date time library, in order to support as many localizations as possible. We are not familiar enough with the different time localization formats, so working with custom formats is extremely difficult

**Comment by jprochazk** [comment]
From package.json, it looks like you're using dayjs. It provides various localized formats: https://day.js.org/docs/en/display/format#localized-formats

Are PRs welcome?

**Comment by sphinxrave** [comment]
PRs totally welcome :D please make them into the /dev branch so we can test it on our staging environment.

**Comment by sphinxrave** [comment]
Is this fixed?
