### ISSUE TITLE
Remove a favorite channel from favorites seems to not be working

### ISSUE THREAD

**Issue by tankume** [RiceCakess/Holodex#54]
I have been trying to remove some vtubers channels from my favorite list. I have tried it from a windows using chrome, and from a android using chrome.

When I go to channels, and then to favorites, when I click to remove a channel in the red heart button, it turns grey for 3 seconds, but then it returns to red, and it dosnt get removed. Also, it dosnt work when trying to remove a favorite directly in the individual channel, so curently I think is impossible to remove a channel from favorites

**Comment by sphinxrave** [comment]
please log out and log back in, i think there are some login issues?

**Comment by tankume** [comment]
Thanks, I tried that and it worked.
