### ISSUE TITLE
Wrong duration being shown on some video cards (Holodex API has wrong duration)

### ISSUE THREAD

**Issue by michaelnguyenm** [RiceCakess/Holodex#60]
# Issue

For example, taking a look at Korone's Sonic 2 stream (Holodex shows that it is 12:08:27, which is based on the duration value given by the API, [43707 seconds](https://holodex.net/api/v2/videos/GeD-lKDv87I)):
![image](https://user-images.githubusercontent.com/8785414/110212949-67025400-7e63-11eb-970f-20ead2e14ff3.png)

Actual length (11:54:48 or 42888 seconds, YouTube API gives PT11H54M48S for contentDetails):
![image](https://user-images.githubusercontent.com/8785414/110212918-40dcb400-7e63-11eb-9f61-0d9afab2c084.png)

This does not appear to be exclusive to videos with long durations either. For example, a recent stream from Lamy is displayed as 48:38 (Holodex API gives [2918 seconds](https://holodex.net/api/v2/videos/juGIlXkxX6k)):
![image](https://user-images.githubusercontent.com/8785414/110213328-2dcae380-7e65-11eb-8323-c25f3b636776.png)

Actual length (47:59 or 2879 seconds, Youtube API gives PT47M59S):
![image](https://user-images.githubusercontent.com/8785414/110213451-b8134780-7e65-11eb-9552-e9d3a14dd9e5.png)

# Other cases

I do not think this is a result of the video being cut down/edited because live chat has been preserved. Here are some other cases (including the above):

Video ID | Youtube API Duration | Expected YT Duration in Seconds | Holodex API Duration | Holodex Formatted
-------- | ----------------------- | ---------------------------------- | ------------------ | --------------------
YRKZnRale5g | PT11H35M6S (11:35:06) | 41706 | Undefined | Undefined
GeD-lKDv87I | PT11H54M48S (11:54:48) | 42888 |  43707 |  12:08:27
P4xuSCEjD5Q | PT11H55M (11:55:00) | 42889 | 43387 | 12:03:07
juGIlXkxX6k | PT47M59S (47:59) | 2879 | 2918 | 48:38
a3NkrpUj1FQ | PT19M7S (19:07) | 1147 | 1261 | 21:01

The top example video (YRKZnRale5g) seems to have some other issue where Holodex API did not provide a duration property for some reason. The bottom video (a3NkrpUj1FQ) is a video premiere in case that could cause some sort of error.

**Comment by jprochazk** [comment]
The frontend seems to format the duration correctly, even though there is an existing issue about this in `dayjs` (https://github.com/iamkun/dayjs/issues/1433), it doesn't seem to be related, because the time scales are different (issue is about months, not hours/minutes/seconds).

The most likely culprit is the backend, which may be returning wrong video durations. It may be an issue with parsing youtube's duration format, or something along those lines.

**Comment by RiceCakess** [comment]
The problem was that the backend was calculating the duration values using start and end times, instead of the YouTube provided duration.

Fixed now.
