### ISSUE TITLE
Support for timestamps in description

### ISSUE THREAD

**Issue by michaelnguyenm** [RiceCakess/Holodex#62]
Some clips have timestamps in their description but they are not clickable. These are common in clips from compilers such as Ritore and Nijisanji English Official:

[[Hololive Compilation] Ritore's Translator Choice #31 [2/28]](https://holodex.net/watch/aD9VesIHrE8)
![image](https://user-images.githubusercontent.com/8785414/110216468-03812200-7e75-11eb-9210-663f5cea4763.png)

[Debut Highlights of the New Five NIJISANJI Members! (VTuber/NIJISANJI Moments) (Eng Sub)](https://holodex.net/watch/39HDGwHuuH0)
![image](https://user-images.githubusercontent.com/8785414/110216477-0b40c680-7e75-11eb-8078-6ab65acde63a.png)

**Comment by sphinxrave** [comment]
![image](https://user-images.githubusercontent.com/62570796/110227118-d7cc5f00-7ea9-11eb-8bba-5a3fdd0f6e01.png)
