### ISSUE TITLE
[Feature request] Please make links respect ctrl+click (open in new tab)

### ISSUE THREAD

**Issue by 29988122** [RiceCakess/Holodex#64]
Situation:
Sometimes it's convenient to click on some vtuber's stream, and batch-open clips of that stream on the right side.

Current behavior:
You can't ctrl+click on the clips, it will open in the same page.

Desired behavior:
The clips on the right side of the stream should respect ctrl+click, and open the link in new tabs.

Or even better - add an option to open every clips (of that stream) in multiple new tabs/in a playlist inside holodex.

Thank you for developing such a great website for us DD!

**Comment by Wuzado** [comment]
For now, you can work around it using a middle mouse click, but I assume that might be troubling for people using touchpads. (Don't have a very good experience using touchpad gestures...)
