### ISSUE TITLE
"Show TLs" button in chat window overlapping with Chat Selector

### ISSUE THREAD

**Issue by nocturne32** [RiceCakess/Holodex#89]
Not sure if this should be an issue or how you look at this problem since Chat Selector is a third party extension for youtube. Still, it is a handy feature to use when there are alot of spam messages. 

The button "Show TLs" is overlapping with Chat Selector for Youtube (making it impossible to interact with) like so:
![image](https://user-images.githubusercontent.com/18268621/112747990-48eac800-8fb9-11eb-86b0-39e0aa116361.png)

It is nothing but a minor inconvenience. Love your work either way.

**Comment by planetarian** [comment]
Same with ytcFilter.
![image](https://user-images.githubusercontent.com/1724041/112748960-ed9ee280-8f84-11eb-8dc7-0650578a3bd1.png)

**Comment by Sininenblue** [comment]
Same with HyperChat
![image](https://user-images.githubusercontent.com/64654751/112749469-edd6c680-8ff4-11eb-8c7a-465114f0387f.png)

**Comment by jprochazk** [comment]
The `Show TLs` button is inside the chat's overlay. Supporting extensions which rely on monkey patching would require either monkey patching the `Show TLs` button, or moving the button elsewhere.

**Comment by nocturne32** [comment]
> supporting them would require either injecting the `Show TLs` button once the chat has loaded, or moving the button elsewhere.

I completely understand. If moving or injecting the button would mess up other things in the app, then we can just close this issue.

**Comment by jprochazk** [comment]
It doesn't mess things up, the button just has to be moved. 🙂 Overall, youtube chat is poor in many ways (resource usage, spam filtering, etc.), so I think making this change to support extensions which modify the youtube chat is justified.
