### ISSUE TITLE
Sign in with Apple

### ISSUE THREAD

**Issue by thebitstick** [RiceCakess/Holodex#99]
Google/Discord/Twitter are included as Login Methods, but a 'Sign in with Apple' option would be appreciated.

**Comment by sphinxrave** [comment]
Requires a developer account that costs $99 a year if i recall correctly. Unnecessary expenditure for a glorified identity check.

When you log into any of the services on the site all we do using it is validate your uniqueness and confirm with the external service you are who you claim to be. 

All we fetch is the basic uniquely identifying unit at the smallest possible scope level each service gave us. 
Your discord UUID + handle (`identity` scope)
Or your twitter UUID + handle (unfortunately Twitter's lowest possible privacy level also lets us read your timeline but i can always see your public timeline anyway so 🤷)
Or your google Email (which we also use as your username). (`auth.email` scope, i think?)

In return, we don't store passwords, or have to deal with passwords, or need to deal with security related to passwords. Absolute win.

**Comment by thebitstick** [comment]
Oh wow. I knew about the $99 developer account for app development, but I didn't know Sign In required that as well. That's such a high barrier.
Sorry for asking!
